//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP2_122_Cheban_Aleksandra
{
    using System;
    using System.Collections.Generic;
    
    public partial class ads_data
    {
        public int id { get; set; }
        public int user_login { get; set; }
        public int user_password { get; set; }
        public int ad_title { get; set; }
        public int ad_description { get; set; }
        public int ad_post_date { get; set; }
        public int city { get; set; }
        public int category { get; set; }
        public int ad_type { get; set; }
        public int ad_status { get; set; }
        public int price { get; set; }
    
        public virtual Ad_description Ad_description1 { get; set; }
        public virtual Ad_post_date Ad_post_date1 { get; set; }
        public virtual Ad_status Ad_status1 { get; set; }
        public virtual Ad_title Ad_title1 { get; set; }
        public virtual Ad_type Ad_type1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual City City1 { get; set; }
        public virtual User_login User_login1 { get; set; }
        public virtual User_password User_password1 { get; set; }
    }
}
