//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP2_122_Cheban_Aleksandra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad_description> Ad_description { get; set; }
        public virtual DbSet<Ad_post_date> Ad_post_date { get; set; }
        public virtual DbSet<Ad_status> Ad_status { get; set; }
        public virtual DbSet<Ad_title> Ad_title { get; set; }
        public virtual DbSet<Ad_type> Ad_type { get; set; }
        public virtual DbSet<ads_data> ads_data { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<User_login> User_login { get; set; }
        public virtual DbSet<User_password> User_password { get; set; }
    }
}
